### ISSUE TITLE
Background Actions

### ISSUE THREAD

**Issue by sboahen** [kd1889/Internet-Radio-for-Kids#10]
- [x] Sound output (music being played)
- [x] Display options (name of track or station, and/or time . . .)

**Comment by sboahen** [comment]
Added starter code: c310a89f8058f6ee4cf2f8fd14f47b5ccc040304
The starter code in the demo will have the main program components moved to radio.py once finalized. Pages (such as home or current track playing) will be created and from the base class Page. 

**NB** Will need to probably add configuration for two lines for the lcd and change the setup

**Comment by sboahen** [comment]
Added functionality to move the cursor through positions on the lcd display: c1b421f076fccaa81a73f841477604d7a46d8fc7

**Comment by sboahen** [comment]
Updated starter code to update lcd screen when button is pushed: e55ede97f9d67f710cae493432fe439032ba60dc
In this commit, only buttons 1 and 3 are activate for home page and radio menu, respectively

This will be a model which will be moved to radio.py after review

**Comment by sboahen** [comment]
Updated button_lcd_demo.py to scroll through track and radio options: **6a91370**

**Comment by sboahen** [comment]
Added functionality for MusicPlayer prototype: 295bb43

Updates for playing music will be placed MusicPlayer play_track method. TrackList attribute should be updated accordingly
A similar Player can be created for PlaySomething page by either creating a new class or merging with MusicPlayer to behave differently based on button pushed

**Comment by kd1889** [comment]
Successfully emitted sound from radio and music player in the background while continuing to display the menu options. Selecting the menu options did not interrupt either services.
Cannot attach sound files but recorded the demonstration
