### ISSUE TITLE
Radio station researach

### ISSUE THREAD

**Issue by kd1889** [kd1889/Internet-Radio-for-Kids#12]
- [x] research different libraries to enable interfacing with radio stations
- [x] research different kid friendly radio stations
- [ ] look into contemporary music apps, like spotify, to implement in radio

**Comment by kd1889** [comment]
Alternative way to stream music (Extra)
[Volumio](https://volumio.org/)
A music player for high quality music playback. Does not inherently have a method to connect with online radio stations but can act as an alternative to pygame. A possible issue is that it does not look command-line friendly, and would require the Pi to be connected to a display. We can get around this using VNC, but not sure how it would interact with other components of the code.

[MoOde](https://moodeaudio.org/)
Similar to Volumio.

Upon further research, the Volumio component is more like an OS rather than an application. Volumio is not an alternative because of this.
1. Connecting to/playing online radio stations

[MPD/MPC](https://learn.adafruit.com/raspberry-pi-radio-player-with-touchscreen/installing-the-music-player-daemon)
Music player client and music player daemon. Allows connecting to online radio services using their URL and playing them using command line. However, it looks limited to the command line, and forces us to use the MPC to output sound as opposed to pygame. Further study/research into this to see if we can use it to connect to radio stations and then use pygame to output sound.

[DarkIce/IceCast](https://maker.pro/raspberry-pi/projects/how-to-build-an-internet-radio-station-with-raspberry-pi-darkice-and-icecast)
The following two serve more as implementing a radio station rather than connecting to them. However, they might serve a good references or tools for further research.

[PianoBar](https://6xq.net/pianobar/)
Radio player for Pandora. Provides command-line methods to communicate with Pandora radio. Same issues as MPD/MPC, where we need a more scriptable way to implement it.

2. Kid-Friendly Radio
The goal of this research was to find different radio stations that are targeted towards young children upto teenagers. Focus from contemporary, known sites to more obscure ones.

[iHeartRadio](https://www.iheart.com/genre/kids-family-106/)
Provides a couple of stations targeted towards children with both music and stories. It looks difficult to implement in a Pi setting in the sense that although we could play the music, I am not sure how we could display the information (name of the music, station name, etc.)

[Pandora](https://www.pandora.com/search/kids/all)
Similar to iHeartRadio, we have stations targeted towards children. There is existing player for Pandora, which can tell us the information related to station name and name of the music. 

[KidJam Radio](https://www.kidjamradio.com/)
A single station for music targeted towards older kids (teenagers?). There is a single station to keep track of so certain information is given, and does not need to be updated. Does not have a way to show what is currently being played.

**Comment by sboahen** [comment]
[Spotify](https://developer.spotify.com/documentation/web-api/) has several APIs that could be used in the radio. Specifically, the user, album, tracks, search, player, and playlist APIs will be used in the project if Spotify is chosen. 
To facilitate this, a thorough research in its API implementation and usage will be needed. Some libraries like [requests ](https://requests.readthedocs.io/en/master/) will also be useful when making HTTP requests to Spotify's API.
