### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by kd1889** [kd1889/Internet-Radio-for-Kids#17]
- [x] Using bootstrap and wireframes, create web pages necessary for the User Interface
- [x] Use Flask to interact with User inputs
- [x] Add Radio stations using web UI
- [x] Add music files (.mp3) using web UI
- [x] Edit playlists using web UI

**Comment by sboahen** [comment]
Added skeleton for music uploads: b1fafd5a30f369f6eaf6d773afd218f2435976ce

**Comment by kd1889** [comment]
See Issue#18 regarding issues surrounding display of information

**Comment by kd1889** [comment]
The homepage:
![image](https://user-images.githubusercontent.com/60377164/117078681-54dc4f00-ad08-11eb-86c9-a9a0dd9960c4.png)
Currently, only shows the menu options. In the future, we will add functionalities to create/select users.

The radio menu:
![image](https://user-images.githubusercontent.com/60377164/117078731-74737780-ad08-11eb-83a0-6930296975ef.png)
The radio menu lists all the radio stations currently loaded onto the radio. Using the checkboxes, the users can select which radio stations they want enabled. We used `yaml` to create configuration based on the selections as shown:
![image](https://user-images.githubusercontent.com/60377164/117078852-a84e9d00-ad08-11eb-8138-744f938c8be4.png)
When a station is checked, and the form is submitted, the `radio.yaml` file is updated, particular the `state` of the radio stations.

The music menu:
![image](https://user-images.githubusercontent.com/60377164/117078925-ca481f80-ad08-11eb-958b-4144edd4c6f0.png)
The music menu shows two menu options: playlist and upload music.

The upload music menu:
![image](https://user-images.githubusercontent.com/60377164/117078960-dfbd4980-ad08-11eb-8db1-2891897e628b.png)
The upload music menu has two forms: the name of the song being added, and the actual file. If the file is not `.mp3`, or `.wav`, the upload fails. In the future, we will implement functionalities to upload multiple files at once.

The playlist menu:
![image](https://user-images.githubusercontent.com/60377164/117079101-1e530400-ad09-11eb-96cc-8a665c81b087.png)
Has two more menu options. Playlist 1 and 2. Both are identical barring for song selection. Follows similar procedure to radio menu.

The parental control menu:
![image](https://user-images.githubusercontent.com/60377164/117079159-404c8680-ad09-11eb-97a3-ab63bd7cb24b.png)
Select multiple options for parental control: from a duration of play to a range of active time. If add music/stations is set to disabled, we prevent users from updating radio stations and uploading new music. Editing playlists is still allowed.
Disabled upload page:
![image](https://user-images.githubusercontent.com/60377164/117079301-7ee24100-ad09-11eb-981e-3dc16a84cbe3.png)
Disabled radio page:
![image](https://user-images.githubusercontent.com/60377164/117079319-86a1e580-ad09-11eb-93a0-e013f6a7c831.png)

All pages update corresponding configuration files, and the files are used for the application logic.
