### ISSUE TITLE
Interface Subsystem

### ISSUE THREAD

**Issue by kd1889** [kd1889/Internet-Radio-for-Kids#6]
- [x] Multimeter to locate internally connected pin (mark them using markers)
- [x] Test using DMM
- [x] Connect buttons as input to Pi, use Piscope
- [x] Library function to test buttons
- [x] check if buttons are working
- [x] check if LEDs are working

**Comment by sboahen** [comment]
Updated button tests: e8dadff7576280eed4efa45e0ab8e438f9089375

Test available in commit

**Comment by sboahen** [comment]
Updated led status tests: e685b49d88da827254ce1093775e0d56a0bd44ea

Test available in commit

**Comment by sboahen** [comment]
Notes on testing:

A multimeter was in testing for internally connected pins. MM read 0.000 ohms for internally connected pins and also read the same value for pins with that were connected with a switch (when the button was pressed).

![image](https://user-images.githubusercontent.com/50114909/112003854-a7b2cc00-8af7-11eb-9a10-3ab9d040bf2d.png)

A pulldown resistor was connected as well as a resistor in series with the input GPIO pins (10k and 470 ohms). 

![image](https://user-images.githubusercontent.com/50114909/112005000-b948a380-8af8-11eb-9729-a9b7d89ced1e.png)

**Comment by sboahen** [comment]
The buttons were tested with the commits in this issue.
The results were also observed with piscope:
"UP": 12,
"DOWN": 16,
"LEFT": 20,
"RIGHT": 7,
"SELECT": 8,
![image](https://user-images.githubusercontent.com/50114909/112024267-67107e00-8b0a-11eb-9d48-a7d5bd95e440.png)

**Comment by sboahen** [comment]
led was tested with 3V line 
![image](https://user-images.githubusercontent.com/50114909/112026951-19e1db80-8b0d-11eb-8460-a8b5ec8452c3.png)
