### ISSUE TITLE
Triggered actions

### ISSUE THREAD

**Issue by sboahen** [kd1889/Internet-Radio-for-Kids#9]
- [x] Button input
- [x] Changing the songs
- [x] Button press delay

**Comment by kd1889** [comment]
The state of the radio changed successfully using the input buttons. The stations for the radio were changed successfully. The transition from downloaded content to radio, and vice versa, was also successful. 
See below for terminal output:
![Screenshot 2021-04-18 181102](https://user-images.githubusercontent.com/60377164/115162618-9adfb480-a072-11eb-9866-7b26ad2f622e.png)

**Comment by kd1889** [comment]
Need further work for buttons. Currently, each a button press can be detected more than once, which results in the screen failing to return to the expected state.
